[package]
name = "black-myth-map"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "injector"
path = "src/main.rs"

[lib]
name = "jas_minimap"
crate-type = ["cdylib"]

[dependencies]
# hudhook = { path = "vendor/hudhook", features = [
#   "inject",
#   "dx12",
#   "dx11",
# ], default-features = false }
hudhook = { git = "https://github.com/veeenu/hudhook", rev = "2871d5e7acf04f23af15987c713215d6f58f9f48", features = [
  "inject",
  "dx12",
], default-features = false }
# imgui = "0.12.0"
# imgui-sys = "0.12.0"
tracing = { version = "0.1", features = ["log"], default-features = false }
tracing-subscriber = "0.3"
image = { version = "0.25.2", features = [
  "jpeg",
  "png",
  "webp",
], default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
proc_mem = "0.1.6"
ilhook = "2.1.1"
mem-rs = "0.1.7"
minhook = "0.6.0"
