[package]
name = "black-myth-map"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "injector"
path = "src/main.rs"

[lib]
name = "jas_minimap"
crate-type = ["cdylib"]

[dependencies]
hudhook = { version = "0.8.0", features = [
  "inject",
  "dx12",
], default-features = false }
image = { version = "0.25.2", features = [
  "jpeg",
  "png",
  "webp",
], default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
