# Reference: https://build-cpp.github.io/cmkr/cmake-toml
# to build:
# > cmake -B build
# > cmake --build build --config Release
[project]
name = "b1sdk"
version = "1.0.0"

[target.b1sdk]
type = "static"
sources = ["src/**.cpp", "src/**.rc"]
headers = ["src/**.hpp", "src/**.h"]
include-directories = ["src/"]
link-libraries = []
compile-features = ["cxx_std_23"]
compile-options = ["/GS-", "/bigobj", "/EHa", "/MP"]
